### ISSUE TITLE
Reconsider nomenclature of `EITData` properties concerning pixel impedance

### ISSUE THREAD

**Issue by DaniBodor** [EIT-ALIVE/eitprocessing#154]
Do these properties have the standard nomenclature in the field, or did you come up with them for this module? To me they are a bit confusing, but if this is what they are generally known as, then it's fine.

_Originally posted by @DaniBodor in https://github.com/EIT-ALIVE/eitprocessing/pull/142#discussion_r1514147007_

https://github.com/EIT-ALIVE/eitprocessing/blob/022060ce96463d2da020c80c9538227fc9a268af/eitprocessing/eit_data/__init__.py#L267-L291

**Comment by psomhorst** [comment]
These were removed when moving global impedance to ContinuousData.
