### ISSUE TITLE
Error in verifying `time` variable in `select_by_time`

### ISSUE THREAD

**Issue by wbaccinelli** [EIT-ALIVE/eitprocessing#161]
When calling `select_by_time`, the function verifies that `time` is a property of the object to be sliced. I tried and I always get an error, even if I see with the debugger that time has actually been set. I looked into it and apparently `vars()` list all the writable attributes of the object (`__dict__` method). In the `Sequence`, time is defined in such a way that it is a property of the class but not of the instance, so it is not listed. [Here](https://stackoverflow.com/questions/19907442/explain-dict-attribute) there is a useful explanation.
The verification should be adjusted.

**Comment by DaniBodor** [comment]
Good catch!

So, we should make `Sequence` only inherit from `SelectByIndex`, but not from `SelectByTime`. Then, within `Sequence`, we write a new `select_by_time` function, which calls `select_by_time` on all underlying `DataCollection` objects.

**Comment by DaniBodor** [comment]
Something similar should happen on the `DataCollection` level (slicing all data inside the collection).
