### ISSUE TITLE
fix notebook paths

### ISSUE THREAD

**Issue by drcandacemakedamoore** [EIT-ALIVE/eitprocessing#19]
Due to new file structure notebooks must be updated as follows:

import sys
sys.path.insert(0, '../eitprocessing')
from binreader import Sequence

(for example) otherwise they will not run smoothly

**Comment by DaniBodor** [comment]
I believe these work fine as is if installed via pip. Can you test that this is also true for you?

**Comment by drcandacemakedamoore** [comment]
The notebook (notebooks/eitbinary) is very broken for me. Please run it cell by cell and adjust.
