### ISSUE TITLE
Add sample frequency to ContinuousData

### ISSUE THREAD

**Issue by psomhorst** [EIT-ALIVE/eitprocessing#209]
ContinuousData is assumed to have a somewhat fixed framerate. This framerate is required for some tasks like filtereing.

**Comment by DaniBodor** [comment]
I was actually thinking about this. 
Is this always going to be true? In my microscopy background, I've worked on experiments with e.g. a measurement every 30sec for 8h, then every 10 mins for 16h. More complex cases also exist, albeit rarer, where alternating frequencies occur or specific time points or intervals may be skipped, etc, etc. I imagine similar cases cannot be excluded here either.
So while the frame rate is "somewhat fixed", as in there is some kind of regularity to it, it's not easily definable as a single parameter (but can be as a complex parameter).

**Comment by psomhorst** [comment]
> I was actually thinking about this. Is this always going to be true? In my microscopy background, I've worked on experiments with e.g. a measurement every 30sec for 8h, then every 10 mins for 16h. More complex cases also exist, albeit rarer, where alternating frequencies occur or specific time points or intervals may be skipped, etc, etc. I imagine similar cases cannot be excluded here either. So while the frame rate is "somewhat fixed", as in there is some kind of regularity to it, it's not easily definable as a single parameter (but can be as a complex parameter).

I think this breaks the assumptions for the use of ContinousData, and it should be saved somewhere else, e.g. as multiple ContinousData sets with different framerates, or as SparseData. Most data is recorded at a regular interval. This class is made for that type of data.
