### ISSUE TITLE
automatically render documentation

### ISSUE THREAD

**Issue by DaniBodor** [EIT-ALIVE/eitprocessing#252]
create workflow to automatically render documentation upon new release or by manual trigger.

**Comment by DaniBodor** [comment]
this is done from the mkdocs.yml using [mike](https://github.com/jimporter/mike?tab=readme-ov-file#configuration).
Would be nice to integrate this into the releasing workflow as well.

**Comment by psomhorst** [comment]
This has been fixed with the release of the new documentation. On push to main, the documentation if built and pushed using `mkdocs gh-publish`.
