### ISSUE TITLE
`Sequence` is an existing data structure in Python

### ISSUE THREAD

**Issue by DaniBodor** [EIT-ALIVE/eitprocessing#262]
I recently learned that a `Sequence` is actually an existing [data structure](https://docs.python.org/3/tutorial/datastructures.html) in Python that is quite widespread and generic. It's basically what I would call a "[list-like](https://pythongeeks.org/python-sequences-types-examples/)" (lists, tuples, strings, etc). Also, type checkers such as [mypy](https://mypy.readthedocs.io/en/stable/builtin_types.html#generic-types) consider `Sequence` a generic type.

I know it's pretty awkward at this stage, but we should consider renaming our `Sequence` class to something that is not as easily misinterpreted. 

@psomhorst, @wbaccinelli, what do you think?

**Comment by psomhorst** [comment]
I knew `Sequence` was a standard Python type. However, most people will never interact with it. It's a generic type that is used for type checking only. 

I would vote against renaming it now. If we would have wanted to, the large rewrite would have been a good moment. Now, post-1.0, I would like to keep the codebase stable. There are probably a dozen things we could have done differently, but changing all of them will lead to several breaking changes and a version 5.0 before we know it.
