### ISSUE TITLE
Release workflow fails

### ISSUE THREAD

**Issue by psomhorst** [EIT-ALIVE/eitprocessing#265]
The release workflow fails. I tried twice running the release workflow from `develop`. However, the branch check (see below) fails: https://github.com/EIT-ALIVE/eitprocessing/actions/runs/9870083219.

https://github.com/EIT-ALIVE/eitprocessing/blob/0fe1808d1a3f31123949211629305a446c98c74e/.github/workflows/release_github.yml#L27-L31

Based on the [documentation](https://docs.github.com/en/actions/learn-github-actions/expressions#example), should this be `if: ${{ github.ref_name == 'main' }}`?

**Comment by psomhorst** [comment]
The issue above is now fixed. The workflow still fails when called with `main` (https://github.com/EIT-ALIVE/eitprocessing/actions/runs/9870352864) but continues when called from `develop`.

**Comment by psomhorst** [comment]
However, there is another issue. This one probably takes too much digging for me to understand.

@DaniBodor do you know what could be the problem here?

https://github.com/EIT-ALIVE/eitprocessing/actions/runs/9870359031

**Comment by psomhorst** [comment]
Fixed with https://github.com/EIT-ALIVE/eitprocessing/commit/1dd366ef86a69f0abffb9757ea4d219cd7cf83ca.

**Comment by DaniBodor** [comment]
> Fixed with [1dd366e](https://github.com/EIT-ALIVE/eitprocessing/commit/1dd366ef86a69f0abffb9757ea4d219cd7cf83ca).

I believe (but not 100% sure) that the $ and curly brackets can go altogether, and it would just be `if: github.ref_name == 'main'`

But let's leave it like this now
