### ISSUE TITLE
Release workflow fails when merging

### ISSUE THREAD

**Issue by psomhorst** [EIT-ALIVE/eitprocessing#266]
This one probably takes too much digging for me to understand. 

@DaniBodor do you know what could be the problem here?

https://github.com/EIT-ALIVE/eitprocessing/actions/runs/9870359031

**Comment by psomhorst** [comment]
I managed to fix this. There were some issues:

- actions/checkout@v4 by default checked out the release branch (`develop` in my case). After switching to `main`, this somehow resulted in the merge failing (see message above). I edited the workflow to have actions/checkout@v4 checkout `main` instead, and merge with `origin/develop`. This works.
- `git merge ... --no-commit` and then `git merge --continue` tried opening an editor for the commit message. I changed the second command to `git commit --no-edit`, which uses the default edit message. 

I think this currently works as intended. It took me a few tries to get it right, sorry for the multiple updates to release_github.yml.

**Comment by DaniBodor** [comment]
Are these changed grouped together in a PR somewhere?

**Comment by psomhorst** [comment]
@DaniBodor No, I made the changes on `main` directly, so there is nothing to pull. The changes had to be on main for the action to work anyway, so a PR would not have helped.

Next time, I'll fork the repo, try fixing it in the fork, and then make a PR instead.

It does now work!
