### ISSUE TITLE
After creating of draft release, `main` is merged into `develop` using fast-forward

### ISSUE THREAD

**Issue by psomhorst** [EIT-ALIVE/eitprocessing#267]
Conceptually, `develop` and `main` are two separate branches. After a release is made from `develop`, `main` is merged into `develop`. Because `develop` and `main` have the same tree at that point, this merge is automatically done as a fast-forward merge. At that point, `develop` and `main` point to the exact same commit.

I think it would make more sense to make an actual merge commit, such that this action always leads to two separate branch tips. This should already be the case if a release is made from a branch different than `develop`. 

What do you think, @DaniBodor?

**Comment by DaniBodor** [comment]
I don't really see the issue here, but your suggestion sounds fine as well.

**Comment by psomhorst** [comment]
This has now been fixed with the release of v1.2.0.
