### ISSUE TITLE
Missing dependency 

### ISSUE THREAD

**Issue by psomhorst** [EIT-ALIVE/eitprocessing#299]
`typing_extensions` is used, but is not part of the dependency list. It should only be loaded for type checking, but it is always loaded in eitdata.py.

**Comment by psomhorst** [comment]
@DaniBodor This bug could fly under the radar due to GitHub automations only testing the [dev] install, which includes the `typing_extensions` (via `sphinx-autoapi` and `astroid`). Do you have time to see whether you can also include the normal (or all, including normal and [notebooks]) builds?

**Comment by DaniBodor** [comment]
I see that this got closed before I had time to look into it. Do I still need to look into it?

I thought that `typing_extensions` is a built-in package (similar to `os`), but am not positive.

**Comment by psomhorst** [comment]
The issue itself is closed. The reason I tagged you is that it should have been caught by automated tests long ago, but wasn't because the tests only cover the [dev,publishing] install.

In my clean install with Python 12, typing_extensions is not installed by default.
________________________________
