### ISSUE TITLE
EELI().computer_parameter() should return SparseData

### ISSUE THREAD

**Issue by psomhorst** [EIT-ALIVE/eitprocessing#320]
TIV().compute_parameter() returns a SparseData object, while EELI().compute_parameter() returns an array. I think both
should return a SparseData object.

```py
eeli_data = eeli.compute_parameter(cont_data)  # array 
tiv_data = tiv.compute_parameter(cont_data).values  # grab array from SparseData object
```

**Comment by JulietteFrancovich** [comment]
I think this issue was solved with the pull request I just merged:
[Merge pull request #325 from EIT-ALIVE/320_eeli_sparse_data](https://github.com/EIT-ALIVE/eitprocessing/commit/5f543e1295a68d3c7622c681676174d880a13a78).
