### ISSUE TITLE
Mark GitHub release branches as merged instead of closed

### ISSUE THREAD

**Issue by DaniBodor** [EIT-ALIVE/eitprocessing#335]
the github release action currently marks PRs as "closed" as opposed to "merged", which is confusing because that makes it look like changes were not accepted.

**Comment by psomhorst** [comment]
I just ran into this as well. I think this is a result of how the github_release action works. Currently, it manually merges, and then later closes the PR. 

Could we rewrite this to:

- If releasing form a PR:
  - Make the base of the PR main and merge the PR (`gh pr edit <nr> --base main; gh pr merge <nr> --admin`)
- If releasing from develop:
  - Merge develop into main using https://github.com/marketplace/actions/merge-branch.
- Use the bump-my-version action to bump the version (https://github.com/callowayproject/bump-my-version?tab=readme-ov-file#github-actions)
- Create a release on github (`gh release create ...`)

Tidy could then probably be simplified to merging main into develop using https://github.com/marketplace/actions/merge-branch.

**Comment by DaniBodor** [comment]
I already have a PR open for this. The reason is that I explicitly added a step to close the PR, which was unnecessary. I changed it in that PR and I think that solves the issue.
The action you found might simplify the entire process (looking at it for a few seconds, it seems like either way can be done with that action). At this point, I will leave the PR as is, but if you prefer doing it with this action, then feel free to redo my PR or add on to it.

**Comment by psomhorst** [comment]
Closed with #338
