### ISSUE TITLE
copyright notice on all files

### ISSUE THREAD

**Issue by drcandacemakedamoore** [EIT-ALIVE/eitprocessing#8]
Add a copyright notice on top of all files (see ReSUrfEMG library for example)

**Comment by DaniBodor** [comment]
why do need this on each file? I think it's enough to have a centralized licence in the repo

**Comment by drcandacemakedamoore** [comment]
We don't but in my opinion it looks better in the documentation to have this at the top of each module documentation, and it makes it much easier for people to give credit if they take a module. I have taken once half an entire module with a super permissive license, and because they had this kind of message at the top, I could mostly copy-paste and the attribution and license info was already there

**Comment by drcandacemakedamoore** [comment]
PR #13
