### ISSUE TITLE
Test Draeger data with `Event` on first frame

### ISSUE THREAD

**Issue by DaniBodor** [EIT-ALIVE/eitprocessing#81]
There were issues when loading data starting after the first frame if there was a 'PhaseIndicator' or 'Event' on the first loaded frame. I solved this by reading an additional frame before the first frame, but not storing its data in the `Sequence` object.
I wonder what happens with data where the actual first frame has a similar attribute on the very first frame in the data, as there it is not possible to preload a frame.

https://github.com/EIT-ALIVE/eitprocessing/blob/27023526d46a6935911bab76f3c62e981e0b93c0/tests/test_sequence.py#L208-L221

**Comment by psomhorst** [comment]
Fixed and tested in #251
